name: Create Archive
on:
  workflow_dispatch:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'Chapter-10.zip'
        files: ./*
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Chapter-10.zip"
        token: ${{ secrets.GITHUB_TOKEN }}