name: Create Archive
on:
  workflow_dispatch:
    branches: [ main ]

env:
  CHAPTER: 10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: create tag
      shell: bash
      id: tag
      run: echo "tag=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - name: create filename
      shell: bash
      id: file
      run: echo "filename=${{ github.event.repository.name }}-chapter-${{ env.CHAPTER }}-updated-${{ env.tag }}.zip" >> $GITHUB_ENV
    - name: display variables
      shell: bash
      run: |
        echo "tag=${{ env.tag }}"
        echo "filename=${{ env.filename }}"
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: '${{ env.filename }}'
        files: ./*
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.filename }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: "${{ env.tag }}"